/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as DeepDiveRouteImport } from './routes/deep-dive'
import { Route as IndexRouteImport } from './routes/index'

const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDiveRoute = DeepDiveRouteImport.update({
  id: '/deep-dive',
  path: '/deep-dive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deep-dive': typeof DeepDiveRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deep-dive': typeof DeepDiveRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deep-dive': typeof DeepDiveRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deep-dive' | '/secretary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deep-dive' | '/secretary'
  id: '__root__' | '/' | '/deep-dive' | '/secretary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeepDiveRoute: typeof DeepDiveRoute
  SecretaryRoute: typeof SecretaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-dive': {
      id: '/deep-dive'
      path: '/deep-dive'
      fullPath: '/deep-dive'
      preLoaderRoute: typeof DeepDiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeepDiveRoute: DeepDiveRoute,
  SecretaryRoute: SecretaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
